==> Create Folder open cmd in that folder

Microsoft Windows [Version 10.0.19045.2965]
(c) Microsoft Corporation. All rights reserved.

E:\djangotutorial>pip install django
Requirement already satisfied: django in c:\users\shubham\appdata\local\programs\python\python311\lib\site-packages (4.2)
Requirement already satisfied: asgiref<4,>=3.6.0 in c:\users\shubham\appdata\local\programs\python\python311\lib\site-packages (from django) (3.6.0)
Requirement already satisfied: sqlparse>=0.3.1 in c:\users\shubham\appdata\local\programs\python\python311\lib\site-packages (from django) (0.4.4)
Requirement already satisfied: tzdata in c:\users\shubham\appdata\local\programs\python\python311\lib\site-packages (from django) (2023.3)

[notice] A new release of pip available: 22.3.1 -> 23.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

E:\djangotutorial>pip install virtualenvwrapper-win
Collecting virtualenvwrapper-win
  Downloading virtualenvwrapper_win-1.2.7-py3-none-any.whl (18 kB)
Collecting virtualenv
  Downloading virtualenv-20.23.0-py3-none-any.whl (3.3 MB)
     ---------------------------------------- 3.3/3.3 MB 1.6 MB/s eta 0:00:00
Collecting distlib<1,>=0.3.6
  Downloading distlib-0.3.6-py2.py3-none-any.whl (468 kB)
     ---------------------------------------- 468.5/468.5 kB 2.9 MB/s eta 0:00:00
Collecting filelock<4,>=3.11
  Downloading filelock-3.12.0-py3-none-any.whl (10 kB)
Collecting platformdirs<4,>=3.2
  Downloading platformdirs-3.5.1-py3-none-any.whl (15 kB)
Installing collected packages: distlib, platformdirs, filelock, virtualenv, virtualenvwrapper-win
Successfully installed distlib-0.3.6 filelock-3.12.0 platformdirs-3.5.1 virtualenv-20.23.0 virtualenvwrapper-win-1.2.7

[notice] A new release of pip available: 22.3.1 -> 23.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

E:\djangotutorial>mkvirtualenv myapp
 C:\Users\Shubham\Envs is not a directory, creating
created virtual environment CPython3.11.3.final.0-64 in 7019ms
  creator CPython3Windows(dest=C:\Users\Shubham\Envs\myapp, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=C:\Users\Shubham\AppData\Local\pypa\virtualenv)
    added seed packages: pip==23.1.2, setuptools==67.7.2, wheel==0.40.0
  activators BashActivator,BatchActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator

(myapp) E:\djangotutorial>pip install django
Collecting django
  Downloading Django-4.2.2-py3-none-any.whl (8.0 MB)
     ---------------------------------------- 8.0/8.0 MB 3.1 MB/s eta 0:00:00
Collecting asgiref<4,>=3.6.0 (from django)
  Downloading asgiref-3.7.2-py3-none-any.whl (24 kB)
Collecting sqlparse>=0.3.1 (from django)
  Using cached sqlparse-0.4.4-py3-none-any.whl (41 kB)
Collecting tzdata (from django)
  Using cached tzdata-2023.3-py2.py3-none-any.whl (341 kB)
Installing collected packages: tzdata, sqlparse, asgiref, django
Successfully installed asgiref-3.7.2 django-4.2.2 sqlparse-0.4.4 tzdata-2023.3

(myapp) E:\djangotutorial>django-admin startproject myproject

(myapp) E:\djangotutorial>dir
 Volume in drive E has no label.
 Volume Serial Number is 9863-E21E

 Directory of E:\djangotutorial

06/09/2023  08:19 PM    <DIR>          .
06/09/2023  08:19 PM    <DIR>          ..
06/09/2023  08:19 PM    <DIR>          myproject
               0 File(s)              0 bytes
               3 Dir(s)  69,943,246,848 bytes free

(myapp) E:\djangotutorial>cd myproject

(myapp) E:\djangotutorial\myproject>dir
 Volume in drive E has no label.
 Volume Serial Number is 9863-E21E

 Directory of E:\djangotutorial\myproject

06/09/2023  08:19 PM    <DIR>          .
06/09/2023  08:19 PM    <DIR>          ..
06/09/2023  08:19 PM               687 manage.py
06/09/2023  08:19 PM    <DIR>          myproject
               1 File(s)            687 bytes
               3 Dir(s)  69,943,246,848 bytes free

(myapp) E:\djangotutorial\myproject>deactivate

E:\djangotutorial\myproject>if defined _OLD_VIRTUAL_PYTHONPATH (set "PYTHONPATH=" )

E:\djangotutorial\myproject>workon myapp
(myapp) E:\djangotutorial\myproject>
(myapp) E:\djangotutorial\myproject> dir
 Volume in drive E has no label.
 Volume Serial Number is 9863-E21E

 Directory of E:\djangotutorial\myproject

06/09/2023  08:19 PM    <DIR>          .
06/09/2023  08:19 PM    <DIR>          ..
06/09/2023  08:19 PM               687 manage.py
06/09/2023  08:19 PM    <DIR>          myproject
               1 File(s)            687 bytes
               3 Dir(s)  69,582,995,456 bytes free

(myapp) E:\djangotutorial\myproject>python manage.py startapp myapp

(myapp) E:\djangotutorial\myproject>python manage.py runserver
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).

You have 18 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, sessions.
Run 'python manage.py migrate' to apply them.
June 09, 2023 - 20:56:45
Django version 4.2.2, using settings 'myproject.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.

[09/Jun/2023 20:58:01] "GET / HTTP/1.1" 200 10664
Not Found: /favicon.ico
[09/Jun/2023 20:58:02] "GET /favicon.ico HTTP/1.1" 404 2113
E:\djangotutorial\myproject\myproject\urls.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

Exception in thread django-main-thread:
Traceback (most recent call last):
  File "C:\Users\Shubham\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\Users\Shubham\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Shubham\Envs\myapp\Lib\site-packages\django\utils\autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\Shubham\Envs\myapp\Lib\site-packages\django\core\management\commands\runserver.py", line 133, in inner_run
    self.check(display_num_errors=True)
  File "C:\Users\Shubham\Envs\myapp\Lib\site-packages\django\core\management\base.py", line 485, in check
    all_issues = checks.run_checks(
                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shubham\Envs\myapp\Lib\site-packages\django\core\checks\registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shubham\Envs\myapp\Lib\site-packages\django\core\checks\urls.py", line 14, in check_url_config
    return check_resolver(resolver)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shubham\Envs\myapp\Lib\site-packages\django\core\checks\urls.py", line 24, in check_resolver
    return check_method()
           ^^^^^^^^^^^^^^
  File "C:\Users\Shubham\Envs\myapp\Lib\site-packages\django\urls\resolvers.py", line 494, in check
    for pattern in self.url_patterns:
                   ^^^^^^^^^^^^^^^^^
  File "C:\Users\Shubham\Envs\myapp\Lib\site-packages\django\utils\functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shubham\Envs\myapp\Lib\site-packages\django\urls\resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shubham\Envs\myapp\Lib\site-packages\django\utils\functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shubham\Envs\myapp\Lib\site-packages\django\urls\resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shubham\AppData\Local\Programs\Python\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\djangotutorial\myproject\myproject\urls.py", line 24, in <module>
    path('', include(myapp.urls))
                     ^^^^^^^^^^
AttributeError: module 'myapp' has no attribute 'urls'
E:\djangotutorial\myproject\myproject\urls.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

Exception in thread django-main-thread:
Traceback (most recent call last):
  File "C:\Users\Shubham\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\Users\Shubham\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Shubham\Envs\myapp\Lib\site-packages\django\utils\autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\Shubham\Envs\myapp\Lib\site-packages\django\core\management\commands\runserver.py", line 133, in inner_run
    self.check(display_num_errors=True)
  File "C:\Users\Shubham\Envs\myapp\Lib\site-packages\django\core\management\base.py", line 485, in check
    all_issues = checks.run_checks(
                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shubham\Envs\myapp\Lib\site-packages\django\core\checks\registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shubham\Envs\myapp\Lib\site-packages\django\core\checks\urls.py", line 14, in check_url_config
    return check_resolver(resolver)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shubham\Envs\myapp\Lib\site-packages\django\core\checks\urls.py", line 24, in check_resolver
    return check_method()
           ^^^^^^^^^^^^^^
  File "C:\Users\Shubham\Envs\myapp\Lib\site-packages\django\urls\resolvers.py", line 494, in check
    for pattern in self.url_patterns:
                   ^^^^^^^^^^^^^^^^^
  File "C:\Users\Shubham\Envs\myapp\Lib\site-packages\django\utils\functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shubham\Envs\myapp\Lib\site-packages\django\urls\resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shubham\Envs\myapp\Lib\site-packages\django\utils\functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shubham\Envs\myapp\Lib\site-packages\django\urls\resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shubham\AppData\Local\Programs\Python\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\djangotutorial\myproject\myproject\urls.py", line 24, in <module>
    path('', include(myapp.urls))
                     ^^^^^^^^^^
AttributeError: module 'myapp' has no attribute 'urls'
E:\djangotutorial\myproject\myproject\urls.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).

You have 18 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, sessions.
Run 'python manage.py migrate' to apply them.
June 09, 2023 - 21:11:59
Django version 4.2.2, using settings 'myproject.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.

[09/Jun/2023 21:12:08] "GET / HTTP/1.1" 200 21
